name: chugli_project65
description: "Zippi – Anonymous, location-based chat rooms for real conversations with people near you."
publish_to: 'none'

version: 1.2.1+5

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.5
  intl: ^0.19.0

  # ── Firebase ──────────────────────────────
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # ── Location ──────────────────────────────
  geolocator: ^13.0.1
  device_info_plus: ^12.4.0
  permission_handler: ^11.3.1
  firebase_messaging: ^15.2.10
  dart_geohash: ^2.1.0
  flutter_local_notifications: ^18.0.1


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
